language: haxe

haxe:
  - "3.2.1"
  - development

sudo: false
addons:
  apt:
    packages:
      - gcc-multilib

os:
  - linux
  - osx

script:
  # Remove all ndll - we want to build them from source
  - rm -rf ndll
  - haxelib install hxcpp
  - make all
  - make install
  - haxe --cwd test/ build-neko.hxml
  - neko test/unit.n
  - haxe --cwd test/ build-cpp.hxml
  - ./test/unit

notifications:
  email: false